repository:
  name: "Go Project"
  description: "Standardized Go development workflow configuration"
  homepage: ""
  topics:
    - go
    - golang
    - standardized-workflows
  
  # Repository settings
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  
  # Default branch
  default_branch: "main"
  
  # Security and analysis
  delete_branch_on_merge: true
  
  # Allow these merge types
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: false
  
  # Branch protection rules
  branch_protection_rules:
    - pattern: "main"
      required_status_checks:
        strict: true
        contexts:
          - "Unit Tests / Go Unit Tests"
          - "Build / Go Build"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: false
      allow_fork_syncing: true

# Collaborators
collaborators: []

# Teams
teams: []
