# x-release-please-version v0.2.2
---
# Name as it appears on the Actions tab of GitHub (for current repo; this gets ignored if called from another repo)
name: Unit Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
  pull_request:

jobs:
  test:
    name: Go
    uses: sassy-bulldog/.github/.github/workflows/units-go.yml@v0.2.2 # x-release-please-version
    secrets: inherit
