# v0.2.2 # x-release-please-version
---
# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: Unit Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
  pull_request_target:

jobs:
  test:
    name: Python
    uses: sassy-bulldog/.github/.github/workflows/units-python.yml@v0.2.2 # x-release-please-version
    secrets: inherit
