# x-release-please-version
name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deployment-target:
        description: 'Deployment target'
        required: true
        default: 'package'
        type: choice
        options:
          - package
          - shiny
          - docker
          - cran

jobs:
  deploy:
    name: R Deploy
    uses: sassy-bulldog/.github/.github/workflows/deploy-R-lang.yml@v0.2.2 # x-release-please-version
    with:
      runs-on: '["ubuntu-latest"]'
      environment: ${{ inputs.environment }}
      artifact-name: 'R-build-artifacts'
      deployment-target: ${{ inputs.deployment-target }}
      version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.1-alpha' }}
