# version: 1.0.0
# Name as it appears on the Actions tab of GitHub 
# (for current repo; this get's ignored if called from another repo)
---
name: Lint Code

# Controls when the workflow will run
on:
  push:
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
  pull_request_target:

# Down scope as necessary via 
# yamllint disable-line rule:line-length
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-terraform-linters:
    name: terraform
    # yamllint disable-line rule:line-length
    uses: sassy-bulldog/.github/.github/workflows/lint-terraform.yml@v0.3.0 # x-release-please-version
    secrets: inherit
