# x-release-please-component-version terraform
# Name as it appears on the Actions tab of GitHub (for current repo; this get's ignored if called from another repo)
name: Unit Tests

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Terraform
    run: |
      echo "Needs to be configured!!!"
      exit 1;
