version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
      - '🚀 CI/CD'
    assignees:
      - 'sassy-bulldog/tsc'
    commit-message:
      prefix: 'chore(deps-ci)'
