name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deployment-target:
        description: 'Deployment target'
        required: true
        default: 'binary'
        type: choice
        options:
          - binary
          - docker
          - k8s
          - serverless
          - crates

jobs:
  deploy:
    name: Rust Deploy
    uses: sassy-bulldog/.github/.github/workflows/deploy-rust.yml@v3.6.1 # x-release-please-version
    with:
      runs-on: '["ubuntu-latest"]'
      environment: ${{ inputs.environment }}
      artifact-name: 'rust-build-artifacts'
      deployment-target: ${{ inputs.deployment-target }}
      version: ${{ inputs.version }}
