# x-release-please-component-version rust
# Name as it appears on the Actions tab of GitHub (for current repo; this gets ignored if called from another repo)
name: 'Unit Tests'

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'releases/**'
      - main
      - rc/*
      - rc
      - beta/*
      - beta
      - alpha/*
      - alpha
  pull_request:

jobs:
  test:
    name: Shared Workflow
    uses: sassy-bulldog/.github/.github/workflows/units-rust.yml@v0.2.2 # x-release-please-component-version rust
    secrets: inherit
