# x-release-please-component-version r-lang
name: Build

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    name: R Build
    uses: sassy-bulldog/.github/.github/workflows/build-r.yml@R-v1.0.0 # x-release-please-component-version r-lang
    with:
      runs-on: '["ubuntu-latest"]'
      artifact-name: 'r-build-artifacts'
      version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.1-alpha' }}
