# x-release-please-component-version SSIS
name: Build

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    name: SSIS Build
    uses: sassy-bulldog/.github/.github/workflows/build-SSIS.yml@SSIS-v1.0.0 # x-release-please-component-version SSIS
    with:
      runs-on: '["ubuntu-latest"]'
      artifact-name: 'SSIS-build-artifacts'
      version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.1-alpha' }}
