# x-release-please-component-version SSDT
name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deployment-target:
        description: 'Deployment target'
        required: true
        default: 'binary'
        type: choice
        options:
          - binary
          - docker
          - k8s
          - serverless
      version:
        description: 'Semantic version to deploy'
        required: false
        default: '0.0.1'
        type: string

jobs:
  deploy:
    name: SSDT Deploy
    uses: sassy-bulldog/.github/.github/workflows/deploy-ssdt.yml@SSDT-v1.0.0 # x-release-please-component-version SSDT
    with:
      runs-on: '["ubuntu-latest"]'
      environment: ${{ github.event.inputs.environment }}
      artifact-name: 'ssdt-build-artifacts'
      version: ${{ github.event.inputs.version }}
      deployment-target: ${{ github.event.inputs.deployment-target }}
