# This file configures pre-commit hooks for the repository.
# It defines the tools and checks that will run automatically before each
# commit, helping to enforce code quality, formatting, and best practices.
# For more information, see:
#   https://pre-commit.com/
---
fail_fast: false
minimum_pre_commit_version: "2.6.0"

ci:
    autofix_commit_msg: 'chore(pre-commit.ci): Auto fixes [...]'
    autoupdate_commit_msg: 'chore(pre-commit.ci): Auto update of pre-commit hooks'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.6.2
    hooks:
    - id: prettier
      types_or: [yaml, json, markdown]

  - repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.4.0
    hooks:
      - id: php-lint
      - id: php-cs-fixer

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
