name: 'Code-Owners are Team(s)'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Additional required tags for the pipeline agents to use.
        required: false
        type: string
        default: '[ "ubuntu-latest" ]'
  push:
    paths:
      - '.github/workflows/codeowners.yml'
      - CODEOWNERS
  pull_request_target:
    paths:
      - '.github/workflows/codeowners.yml'
      - '**/CODEOWNERS'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  codeowners:
    name: Verify Code Owners per Governance
    runs-on: ${{ fromJSON(inputs.runs-on || '[ "ubuntu-latest" ]') }}
    steps:
      #TODO: Deprecated NodeJS Version
      - name: Clean Agent Workspace
        uses: tiacsys/clean-after-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.base_ref }}

      - name: Check for CODEOWNERS file
        uses: andstor/file-existence-action@v3.0.0
        id: check_codeowners
        with:
          files: '**/CODEOWNERS'

      - name: Validate CODEOWNERS
        uses: mszostok/codeowners-validator@v0.7.5-rc1
        if: steps.check_codeowners.outputs.files_exists
        with:
          checks: "owners,duppatterns,syntax"
          # github_access_token: ${{ steps.decrypt-token.outputs.out }}
          GITHUB_APP_ID: ${{ vars.GOV_APP_CLIENT_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ vars.GOV_APP_INSTALLATION_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GOV_APP_PVT_KEY }}
          owner_checker_owners_must_be_teams: true
          # owner_checker_ignored_owners:
