# x-release-please-version v0.2.2
---
name: 'Issue & PR Maintenance'

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      runs-on:
        description: Additional required tags for the pipeline agents to use.
        required: false
        type: string
        default: '[ "ubuntu-latest" ]'

  schedule:
    - cron: '0 0 * * *'

  push:
    paths:
      - '.github/workflows/stale.yml'

jobs:
  get-app-token:
    name: Get GitHub App Token
    uses: ./.github/workflows/get-app-token.yml
    with:
      runs-on: ${{ inputs.runs-on || '[ "ubuntu-latest" ]' }}
      client-id: ${{ vars.GOV_APP_CLIENT_ID }}
      installation-id: ${{ vars.GOV_APP_INSTALLATION_ID }}
    secrets: inherit

  stale:
    name: Close Issues w/o Update for 10-days, Mark Issues and PRs Older than 90-days as Stale
    needs: get-app-token
    runs-on: ${{ fromJSON(inputs.runs-on || '[ "ubuntu-latest" ]') }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Clean Agent Workspace
        uses: tiacsys/clean-after-action@v3.0.0

      - name: Decrypt Token
        uses: cloudposse/github-action-secret-outputs@0.1.2
        id: decrypt-token
        with:
          ## PASSWORD is a gpg passphrase stored in Github Secrets.
          secret: ${{ secrets.GOV_APP_PASSWORD }}
          op: decode
          in: ${{ needs.get-app-token.outputs.encrypted-token }}

      - name: Stale Issues and PRs
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ steps.decrypt-token.outputs.out }}
          # Staling issues and PR's
          days-before-stale: 90
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open 90 days
            with no activity. Remove stale label or comment or this issue will be closed in 10 days
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open 90 days
            with no activity. Remove stale label or comment or this PR will be closed in 10 days
          # Not stale if have this labels or part of milestone
          exempt-issue-labels: bug,wip,on-hold
          exempt-pr-labels: bug,wip,on-hold
          exempt-all-milestones: true
          # Close issue operations
          # Label will be automatically removed if the issues are no longer closed nor locked.
          days-before-close: 10
          delete-branch: true
          close-issue-message: This issue was automatically closed because it remained marked as stale for 10 days
          close-pr-message: This PR was automatically closed because remained marked as stale for 10 days

  lock:
    name: Lock issues and PRs that have been closed for 60-days
    needs: get-app-token
    runs-on: ${{ fromJSON(inputs.runs-on || '[ "ubuntu-latest" ]') }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      #TODO: Deprecated NodeJS Version
      - name: Clean Agent Workspace
        uses: tiacsys/clean-after-action@v3.0.0

      - name: Decrypt Token
        uses: cloudposse/github-action-secret-outputs@0.1.2
        id: decrypt-token
        with:
          ## PASSWORD is a gpg passphrase stored in Github Secrets.
          secret: ${{ secrets.GOV_APP_PASSWORD }}
          op: decode
          in: ${{ needs.get-app-token.outputs.encrypted-token }}

      - name: Lock Threads
        uses: dessant/lock-threads@v5.0.1
        with:
          github-token: ${{ steps.decrypt-token.outputs.out }}
          issue-comment: >
            I'm going to lock this issue because it has been closed for _60 days_ ⏳. This helps our maintainers find and focus on the active issues.
            If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
          issue-inactive-days: '60'
          pr-comment: >
            I'm going to lock this pull request because it has been closed for _60 days_ ⏳. This helps our maintainers find and focus on the active issues.
            If you have found a problem that seems related to this change, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
          pr-inactive-days: '60'
